FROM debian

ENV TEAMSPEAK_URL http://dl.4players.de/ts/releases/3.0.11.2/teamspeak3-server_linux-amd64-3.0.11.2.tar.gz

RUN apt -y install tar

ADD ${TEAMSPEAK_URL} /teamspeak/installed/

RUN cd /teamspeak/ && tar -xzf /teamspeak/installed/teamspeak3-server_linux-amd64-3.0.11.2.tar.gz

EXPOSE 9987:9987/udp

ENTRYPOINT ["/teamspeak/teamspeak3-server_linux-amd64/ts3server_minimal_runscript.sh"]