FROM ruby

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs sqlite3

ONBUILD COPY app /opt/app
ONBUILD WORKDIR /opt/app

ONBUILD EXPOSE 3000
ONBUILD RUN bundle install && bundler install --jobs 20 --retry 5
ONBUILD RUN rake db:migrate
ONBUILD RUN rake db:seed